language: go

sudo: false

go:
  - 1.4

install:
  - npm install -g bower
  - go get github.com/jteeuwen/go-bindata/...
  - go get github.com/laher/goxc


script:
  - bower install
  - go generate
  - goxc -d .
