language: go
sudo: false
go: '1.12'
addons:
  apt:
    packages:
      - libgconf-2.4 # workaround for cypress. see https://github.com/cypress-io/cypress/issues/4069#issuecomment-488315675
install:
- nvm install --lts
- npm ci
- go get github.com/jteeuwen/go-bindata/...
- go get github.com/laher/goxc
env:
- TS_VERSION=${TRAVIS_TAG#v}
script:
- npm test
before_deploy:
- make install
- goxc -d dist -pv "$TS_VERSION"
cache: npm
deploy:
  provider: releases
  skip_cleanup: true
  api_key: ${GITHUB_API_KEY}
  file:
    - dist/$TS_VERSION/ts_${TS_VERSION}_darwin_386.zip
    - dist/$TS_VERSION/ts_${TS_VERSION}_darwin_amd64.zip
    - dist/$TS_VERSION/ts_${TS_VERSION}_linux_386.tar.gz
    - dist/$TS_VERSION/ts_${TS_VERSION}_linux_amd64.tar.gz
    - dist/$TS_VERSION/ts_${TS_VERSION}_windows_386.zip
    - dist/$TS_VERSION/ts_${TS_VERSION}_windows_amd64.zip
  on:
    repo: togostanza/ts
    tags: true
