language: go
sudo: false
go:
- '1.10'
install:
- npm install -g bower
- go get github.com/jteeuwen/go-bindata/...
- go get github.com/laher/goxc
env:
- TS_VERSION=${TRAVIS_TAG#v}
script:
- bower install
- go generate ./...
- goxc -d . -pv "$TS_VERSION"
deploy:
  provider: releases
  api_key: ${GITHUB_API_KEY}
  file:
    - $TS_VERSION/ts_${TS_VERSION}_darwin_386.zip
    - $TS_VERSION/ts_${TS_VERSION}_darwin_amd64.zip
    - $TS_VERSION/ts_${TS_VERSION}_linux_386.tar.gz
    - $TS_VERSION/ts_${TS_VERSION}_linux_amd64.tar.gz
    - $TS_VERSION/ts_${TS_VERSION}_windows_386.zip
    - $TS_VERSION/ts_${TS_VERSION}_windows_amd64.zip
  on:
    repo: togostanza/ts
    tags: true
    go: '1.10'
